source 'https://rubygems.org'
ruby '2.1.5'

gem 'rails', '4.1.8'

gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'therubyracer', platforms: :ruby
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder'
gem 'pg'
gem 'i18n-js'
gem 'devise'
gem 'omniauth-facebook'
gem 'omniauth-twitter'
gem 'omniauth-google-oauth2'
gem 'cancancan'
gem 'friendly_id'
gem 'paperclip'
gem 'aws-sdk'
gem 'breadcrumbs_on_rails'
gem 'kaminari'
gem 'font-awesome-rails'
gem 'less-rails'
gem 'slim-rails'
gem 'uuidtools'
gem 'figaro'
gem 'exception_notification'
gem 'bartt-ssl_requirement', require: 'ssl_requirement'
gem 'activerecord-session_store'
gem 'open_uri_redirections'
gem 'active_attr'
gem 'schema_plus'
gem 'mail-iso-2022-jp'
gem 'browser'
gem 'garage', github: 'cookpad/garage'
gem 'weak_parameters'

group :production, :staging do
  gem 'rails_12factor'
end

group :development, :test do
  gem 'sqlite3'
  gem 'sdoc'
  gem 'autodoc'
  gem 'spring'
  gem 'powder'
  gem 'pry', '< 0.10.0'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'pry-stack_explorer'
  gem 'hirb-unicode'
  gem 'guard-pow'
  gem 'quiet_assets'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'bullet'
  gem 'rack-mini-profiler'
  gem 'letter_opener'
  gem 'letter_opener-iso-2022-jp'
  gem 'annotate'
  gem 'debug_exceptions_json'
  gem 'rspec-rails'
  gem 'turnip'
  gem 'capybara'
  gem 'poltergeist'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'simplecov', require: false
  gem 'simplecov-rcov', require: false
  gem 'capistrano'
  gem 'capistrano-rails'
  gem 'capistrano-bundler'
  gem 'capistrano-rbenv'
end
